#!/usr/bin/python3.5
import os
import connection
import configparser

# Read config file
config = configparser.ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), "../config/config"))
baseUrl = config.get("Server", "Url")

# Sets up api connection
s = connection.connect()
# Send request to retrieve orders
users = s.get(baseUrl + "/users")
[print(user['email']) for user in users.json()]
